---
db:
  type: mysql
  host: localhost
  name: opar
  user: root
  pass: 
paths:
  base: /Users/tk/Desktop/Renee/OPAR/opar-web/
  templates: templates/
  conf: /Users/tk/Desktop/Renee/OPAR/opar-web/conf/
  static: static/
  mails: mails/
  uploads: /Users/tk/Desktop/Renee/OPAR/opar-web/uploads/
defaults:
  static: imprint
templates:
  base: opar.tmpl
  author: author.tmpl
  admin: admin.tmpl
logging: logging.web.conf
formid:
  expire: 300
  passwd_expire: 86400
time:
  deletion: 259200
recaptcha:
  public_key: public
  private_key: private
mail:
  smtp:
    host: your_smtp.example
    user: smtp_user
    pass: smtp_password
  from: opar@fqdn.example
  to: you@fqdn.example
  subjects:
    general: Mail from OPAR
    forgot_password: Forgot password
    registration: Account for OPAR requested
  tag: [OPAR]
password:
  salt: OPAR
admin:
  startpage: menu
errors:
  captcha:
    headline: Captcha not Correct!
    message: Your captcha solution was wrong.
  formid:
    headline: Invalid FormID!
    message: The form id expired, please try again.
  input:
    headline: Invalid Input!
    message: One or more fields were not filled or not filled correctly.
  package_not_found:
    headline: Package not Found!
    message: The package you have requested cannot be found.
  username_exists:
    headline: User already exists!
    message: The username you have chosen is already in use.
utils:
  config: /home/opar/opar_sources/conf
  perltidy:
    config: perltidyrc
  perlcritic:
    config: perlcriticrc
general:
  perl_version: 5.008001
help:
  registration:
    username: Username has to be longer than 3 characters (A-Z, a-z), no special characters
    email: Must be in valid email format
